# Use root as user credentials
version: "3.1"

services:
  mysql:
    image: mysql:8.0.19
    restart: always
    environment:
      MYSQL_DATABASE: hsondb
      MYSQL_ROOT_PASSWORD: localmysqlpwd123
      TZ: Asia/Seoul
    ports:
      - 3307:3306
    command: ['mysqld', '--sql_mode=NO_ENGINE_SUBSTITUTION', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  redis:
    image: redis:5.0.6
    restart: always
    ports:
      - 6370:6379

networks:
  default:
    external:
      name: mysql
